config/routes.rb
Rails.application.routes.draw do
  root 'application#home'
  get 'projects', to: 'application#projects'
  get 'documentation', to: 'application#documentation'
  get 'aboutme', to: 'application#aboutme'
  get 'contact', to: 'application#contact'
  get 'apple', to: 'application#apple'
  get 'webscraping', to:'application#webscraping'
  get 'police', to:'application#police'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def home
  end
  def projects
  end
  def documentation
  end
  def aboutme
  end
  def apple
  end
  def webscraping
  end
  def police
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_article.html.erb
<article class="media offset is-size-4 fadein">
<figure class="media-left">
  <p class="image is-96x96">
    <%= image_tag(image) %>
  </p>
</figure>
<div class="media-content">
  <div class="content">
    <%= link_to(link) do %>
    <p>
      <strong><%=title%></strong>  <small><%=date %></small>
      <% end %>

      <br>
      <%=description%>
    </p>
  </div>

</div>

</article>

app/views/application/_navbar.html.erb
<nav class="navbar">
    <div class="container">
        <div class="navbar-brand">
          <span class="navbar-item">
              <%= link_to(root_path, class: "button is-#{color} is-outlined") do %>
                  <span class="icon has-text-info">
                      <i class="fa fa-home"></i>
                  </span>
                  <span>Home</span>
              <% end %>
          </span>
            <span class="navbar-burger burger" data-target="navbarMenu">
                <span></span>
                <span></span>
                <span></span>
            </span>
        </div>
        <div id="navbarMenu" class="navbar-menu">
            <div class="navbar-end">

                <span class="navbar-item">
                    <a class="button is-<%=color%> is-outlined" href="https://www.linkedin.com/in/andrew-fleischer1997/" target="_blank">
                        <span class="icon has-text-info">
                            <i class="fa fa-linkedin-square"></i>
                        </span>
                        <span>LinkedIn</span>
                    </a>
                </span>
                <span class="navbar-item">
                    <a class="button is-<%=color%> is-outlined" href="https://github.com/Flysure" target="_blank">
                        <span class="icon has-text-info">
                            <i class="fa fa-github"></i>
                        </span>
                        <span>Github</span>
                    </a>
                </span>
            </div>
        </div>
        </div>
</nav>

app/views/application/home.html.erb
    <section class="hero is-info is-fullheight">
        <div class="hero-head">
            <%= render(:partial => "navbar", :locals => {:color => "white"}) %>
            </div>

            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-6 is-offset-3">
                        <h1 class="title is-1">
                            Andrew Fleischer
                        </h1>
                        <%= link_to(projects_path, class: "button is-white is-outlined is-large") do %>
                              <span class="icon">
                                  <i class="fa fa-superpowers"></i>
                              </span>
                              <span>Projects</span>
                          <% end %>
                        <h2 class="subtitle is-6">
                          <i>Computer Science student and aspiring technology professional</i>
                        </h2>


                    </div>
                </div>
            </div>

    </section>

app/views/application/police.html.erb
<script type="text/javascript" src='https://cdn.jsdelivr.net/gh/emn178/chartjs-plugin-labels/src/chartjs-plugin-labels.js'>

</script>
<div class="container">
  <nav class="navbar">
          <div class="navbar-brand">
            <span class="navbar-item">
                <%= link_to(root_path, class: "button is-black is-outlined") do %>
                    <span class="icon has-text-info">
                        <i class="fa fa-home"></i>
                    </span>
                    <span>Home</span>
                <% end %>
            </span>
              <span class="navbar-burger burger" data-target="navbarMenu">
                  <span></span>
                  <span></span>
                  <span></span>
              </span>
          </div>
          <div id="navbarMenu" class="navbar-menu">
              <div class="navbar-end">
                <span class="navbar-item">
                  <%= link_to(projects_path, class: "button is-black is-outlined") do %>
                        <span class="icon has-text-info">
                            <i class="fa fa-superpowers"></i>
                        </span>
                        <span>Projects</span>
                    <% end %>
                </span>
                  <span class="navbar-item">
                      <a class="button is-black is-outlined" href="https://www.linkedin.com/in/andrew-fleischer1997/" target="_blank">
                          <span class="icon has-text-info">
                              <i class="fa fa-linkedin-square"></i>
                          </span>
                          <span>LinkedIn</span>
                      </a>
                  </span>
                  <span class="navbar-item">
                      <a class="button is-black is-outlined" href="https://github.com/Flysure" target="_blank">
                          <span class="icon has-text-info">
                              <i class="fa fa-github"></i>
                          </span>
                          <span>Github</span>
                      </a>
                  </span>
              </div>
          </div>
  </nav>
  <div class="content is-size-6 offset fadein">
        <div class="container">
          <h1 class="title is-2">
           Franklin County Traffic Violations
          </h1>
          <h2 class="subtitle is-4">Citations dated from January 2nd, 2018 - April 19th, 2018 in Franklin County, Ohio</h2>
          <p> <a href="https://github.com/Flysure/Data/blob/master/franklin.R">R code</a>, <a href="https://www.smartcolumbusos.com/data">data source</a></p>
        </div>
<hr>

    <div class="columns">
      <div class="column">
        <canvas id="trafSex" width="350" height="200"></canvas>
      </div>
      <div class="column is-one-half">
        <canvas id="trafRace" width="350" height="200"></canvas>
      </div>

    </div>
    <br>
    <br>

    <div class="columns">

      <div class="column box">
        <ul>
<br>
          <li>Offenders were overwhelmingly <strong>male</strong></li>
          <br>
          <br>
          <li>Race was listed as 'W', 'B', or 'O', which I take as meaning white, black, or other.</li>
          <br><br>
          <li>Mondays and Sundays could be biased against because the data begins on a Tuesday and ends on a Sturday, which over-represents the other days.</li>
        </ul>

      </div>
      <div class="column is-two-thirds">
                <canvas id="weekdayTraf"  width="800" height="400"></canvas>
</div>

  </div>
  <br>
  <br>
  <div class="columns">
    <div class="column">
      <h5 class="has-text-centered">Jan 2nd, 2018 - April 19th, 2018</h5>
      <table class='gmisc_table' style='border-collapse: collapse; margin-top: 1em; margin-bottom: 1em;' >
  <thead>
  <tr>
  <th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>Violation</th>
  <th style='border-bottom: 1px solid grey; border-top: 2px solid grey; text-align: center;'>Occurances</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <td style='text-align: center;'>SPEED</td>
  <td style='text-align: center;'>8959</td>
  </tr>
  <tr>
  <td style='text-align: center;'>SEATBELT - OPERATOR</td>
  <td style='text-align: center;'>3357</td>
  </tr>
  <tr>
  <td style='text-align: center;'>DRIVING UNDER SUSPENSION</td>
  <td style='text-align: center;'>2255</td>
  </tr>
  <tr>
  <td style='text-align: center;'>ACDA</td>
  <td style='text-align: center;'>1779</td>
  </tr>
  <tr>
  <td style='text-align: center;'>OVI - IMPAIRED</td>
  <td style='text-align: center;'>1598</td>
  </tr>
  <tr>
  <td style='text-align: center;'>OPERATING MOTOR VEHICLE WITHOUT A VALID LICENSE</td>
  <td style='text-align: center;'>1590</td>
  </tr>
  <tr>
  <td style='text-align: center;'>TRAFFIC CONTROL DEVICE</td>
  <td style='text-align: center;'>1356</td>
  </tr>
  <tr>
  <td style='text-align: center;'>TAG VIOLATIONS</td>
  <td style='text-align: center;'>1305</td>
  </tr>
  <tr>
  <td style='text-align: center;'>NO OPERATORS LICENSE</td>
  <td style='text-align: center;'>1294</td>
  </tr>
  <tr>
  <td style='border-bottom: 2px solid grey; text-align: center;'>FAILURE TO CONTROL</td>
  <td style='border-bottom: 2px solid grey; text-align: center;'>1211</td>
  </tr>
  </tbody>
  </table>

    </div>
    <br>
    <br>
    <div class="column is-two-thirds box">
<br>
      <ul>
        <li>There are several kinds of speeding violations in Ohio. For example, SPEED SCHOOL ZONE - LESS THAN 35 MPH, SPEED PER SE - POSTED FREEWAY, or SPEED - PER SE - 55 MPH. 	</li>
        <ul>
          <li>All the different variations of speeding were grouped together as one, SPEED</li>
        </ul>
        <br>
        <li>"In some ways, 'assured clear distance [ahead]' (ACDA) is a vague concept. It’s part of Ohio law that you have to maintain a speed and distance when driving such that you can come to a
          sudden stop without hitting the car in front of you.
          That distance between you and the other car that allows you to stop without a collision is the 'assured clear distance ahead.'" - <a href="https://www.columbuscriminalattorney.com/traffic-lawyer/assured-clear-distance-ahead/">source</a></li>
<br><br>
        <li>Seatbelt violations were the <strong>3rd</strong> most cited violation</li>
        <br>
        <br>
        <li>Violations steadily rise generally during the day, starting at 7:00 AM, with a peak around 4:00 PM - 5:00 PM</li>
      </ul>

    </div>


  </div>
  <br>
  <br>
<div class="columns">

  <div class="column">
<canvas id="line-chart" width="600" height="300"></canvas>
  </div>
</div>
<br>

</div>
</div>
<br><br><br>
<script>
new Chart(document.getElementById("line-chart"), {
  type: 'line',
  data: {
    labels: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24],
    datasets: [{
        label: 'Violations',
        data: [2257, 2321, 2403, 1208,  565,  389,  402,  841, 1440, 1724, 1927, 1739, 1759, 2011, 2294, 2836, 2881, 2462, 1561, 1407, 1794, 1447, 1284, 1648],
        borderColor: "black",
        fill: false
      }
    ]
  },
  options: {
    title: {
      display: true,
      text: 'Franklin County Traffic Violations Count by Hour, Jan. 2nd 2018 - April 19th, 2018'
    },
    scales: {
        yAxes: [{
          scaleLabel: {
    display: true,
    labelString: 'Violation Count'
  },
            ticks: {
                beginAtZero:true
            }
        }],
        xAxes: [{
          scaleLabel: {
    display: true,
    labelString: 'Hour'
  }}]
    }
  }
});
var ctx = document.getElementById("trafSex").getContext('2d');

var myChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
        datasets: [{
            label: 'Miles',
            data: [12993, 27748],
            backgroundColor:   ['rgb(255, 128, 255, .2)', 'rgb(51, 51, 255, .2)'],
            borderColor:   ['rgb(255, 128, 255)','rgb(51, 51, 255)'],
            borderWidth: 1
        }],
        labels: ["Female","Male"],
    },
    options: {
      title: {
            display: true,
            text: 'Franklin County Traffic Violation Count by Sex, Jan. 2nd 2018 - April 19th, 2018'
        },
      legend: {
            display: true
         },
      responsive: true
    }
});

var ctx = document.getElementById("trafRace").getContext('2d');

var myChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
        datasets: [{
            label: 'Miles',
            data: [19950, 17607, 2962],
            backgroundColor:   ['rgb(255, 140, 102, .2)', 'rgb(102, 179, 255, .2)','rgb(255, 102, 204, .2)'],
            borderColor:   ['rgb(255, 140, 102)','rgb(102, 179, 255)','rgb(255, 102, 204)'],
            borderWidth: 1
        }],
        labels: ["W","B", "O"],
    },
    options: {
      title: {
            display: true,
            text: 'Franklin County Traffic Violation Count by Race, Jan. 2nd 2018 - April 19th, 2018'
        },
      legend: {
            display: true
         },
      responsive: true
    }
});
var ctx = document.getElementById("weekdayTraf").getContext('2d');
var myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
        datasets: [{
            label: 'Count',
            data:[5231,5727,5820,6121,6958,6048,4944],
            backgroundColor: 'rgb(51, 51, 255, .2)',
              borderColor: 'rgb(51, 51, 255)',
            borderWidth: 1
        }]
    },
    options: {
      plugins:{
        labels:{
          render: 'value'
        }
      },
      title: {
            display: true,
            text: 'Franklin County Traffic Violation Count by Weekday, Jan. 2nd 2018 - April 19th, 2018',
            padding: 20
        },
      legend: {
            display: false
         },
      responsive: true,

        scales: {
            yAxes: [{
              scaleLabel: {
        display: true,
        labelString: 'Violations Count'
      },
                ticks: {
                    beginAtZero:true
                }
            }],
            xAxes: [{
              scaleLabel: {
        display: true,
        labelString: 'Weekday'
      }}]
        }
    }
});

</script>

app/views/application/projects.html.erb
<div class="container">
  <%= render(:partial => "navbar", :locals => {:color => "black"}) %>

  <%= render(:partial => "article", :locals => {:image => "police.jpg",
  :title => "Franklin County Traffic Violations", :date => "8/25/2019",
  :link => police_path,
  :description => "Wordpress website of tOSU club STEM Outeach with integration of several plugins."})%>

  <%= render(:partial => "article", :locals => {:image => "buckeye.png",
  :title => "STEM Outreach", :date => "2/08/2019",
  :link => "http://org.osu.edu/stemoutreach/",
  :description => "Wordpress website of tOSU club STEM Outeach with integration of several plugins."})%>

  <%= render(:partial => "article", :locals => {:image => "osu.jpg",
  :title => "Grader Matching Application", :date => "12/13/2018",
  :link => "https://project-6-fcdb.herokuapp.com",
  :description => "OSU CSE 3901 Ruby on Rails final group project that matches graders with classes.
   Involves different types of users and complex modeling."})%>

   <%= render(:partial => "article", :locals => {:image => "scraper-tool.jpg",
   :title => "Webscraping Police Records with Python", :date => "11/7/2018",
   :link => webscraping_path,
   :description => "Pulling records from Columbus Police Portal."})%>

   <%= render(:partial => "article", :locals => {:image => "health-app.png",
   :title => "Health Data Exploration", :date => "8/24/2018",
   :link => apple_path,
   :description => "Exploring my iphone's health data dating back to 2015 using Python. Use of Pandas and Chart.js library."})%>

   <%= render(:partial => "article", :locals => {:image => "pothole.png",
   :title => "Pothole Radar", :date => "8/24/2018",
   :link => "https://pothole-radar.herokuapp.com/potholes",
   :description => "Ruby on Rails application to mark potholes and view potholes around you. Involves the use of
   google maps API and JavaScript-heavy functionality."})%>

   <%= render(:partial => "article", :locals => {:image => "fish.jpg",
   :title => "Alum Creek Fishing", :date => "7/05/2017",
   :link => "https://mysterious-mesa-40318.herokuapp.com/",
   :description => "My first website to display fishing information on Alum Creek wildlife."})%>


</div>
</div>

app/views/application/webscraping.html.erb
<div class="container">
  <nav class="navbar">
          <div class="navbar-brand">
            <span class="navbar-item">
                <%= link_to(root_path, class: "button is-black is-outlined") do %>
                    <span class="icon has-text-info">
                        <i class="fa fa-home"></i>
                    </span>
                    <span>Home</span>
                <% end %>
            </span>
              <span class="navbar-burger burger" data-target="navbarMenu">
                  <span></span>
                  <span></span>
                  <span></span>
              </span>
          </div>
          <div id="navbarMenu" class="navbar-menu">
              <div class="navbar-end">
                <span class="navbar-item">
                  <%= link_to(projects_path, class: "button is-black is-outlined") do %>
                        <span class="icon has-text-info">
                            <i class="fa fa-superpowers"></i>
                        </span>
                        <span>Projects</span>
                    <% end %>
                </span>
                  <span class="navbar-item">
                      <a class="button is-black is-outlined" href="https://www.linkedin.com/in/andrew-fleischer1997/" target="_blank">
                          <span class="icon has-text-info">
                              <i class="fa fa-linkedin-square"></i>
                          </span>
                          <span>LinkedIn</span>
                      </a>
                  </span>
                  <span class="navbar-item">
                      <a class="button is-black is-outlined" href="https://github.com/Flysure" target="_blank">
                          <span class="icon has-text-info">
                              <i class="fa fa-github"></i>
                          </span>
                          <span>Github</span>
                      </a>
                  </span>
              </div>
          </div>
  </nav>
</div>
<div class="container">
  <h1 class="title is-2">
  Webscraping with Selenium Web Driver and Beautiful Soup
  </h1>
  <h2 class="subtitle is-4">Obtaing police records from Columbus Police Portal</h2>
  <div class="content">
    <p>Interested in making an application out of crime data, the goal of this project was to extract that data
    from the Columbus Police Crime Portal. <a href="https://github.com/Flysure/OSU-Crime/blob/master/test.py">This</a> link
    shows the code that was used to scrape the data from google chrome web browser. The program also makes calls to geolocate the
  address listed on the crime portal. The program in action:</p><br>
    <%= image_tag("webscraper.gif", :size => "900x500", :class => "centered-image") %>
  </div>
  <br><br>
  <p>This scraper yeilds <a href="'http://www.columbuspolice.org/Reports/Results?from=9/19/2018&to=9/26/2018&loc=pct4&types=9'">this</a> page
   into a .csv file:</p>
   <br>
   <br>
  <table class="table table-bordered table-hover table-condensed">
<thead><tr>
<th title="Field #2">CRnumber</th>
<th title="Field #3">Description</th>
<th title="Field #4">Victim</th>
<th title="Field #5">DateReported</th>
<th title="Field #6">Location</th>
<th title="Field #7">Lat</th>
<th title="Field #8">Lng</th>
</tr></thead>
<tbody><tr>

<td>180792318-001</td>
<td>450 - Robbery</td>
<td>Benjamin Hamilton</td>
<td>09/19/2018</td>
<td>1960 N High St</td>
<td>40.00233</td>
<td>-83.00849</td>
</tr>
<tr>

<td>180792418-001</td>
<td>551 - Criminal Damaging</td>
<td> [E] Waffle House</td>
<td>09/19/2018</td>
<td>1712 N High St</td>
<td>39.99746</td>
<td>-83.00754</td>
</tr>
<tr>

<td>183016232-001</td>
<td>117 - Theft - From Motor Vehicle - Felony</td>
<td>Danise White</td>
<td>09/19/2018</td>
<td>299 King Ave</td>
<td>39.990437</td>
<td>-83.01409</td>
</tr>
<tr>

<td>180796962-001</td>
<td>400 - Fraud</td>
<td>Mariah Jordan</td>
<td>09/20/2018</td>
<td>1390 Indianola Ave</td>
<td>39.99104</td>
<td>-83.003174</td>
</tr>
<tr>

<td>183016169-001</td>
<td>118 - Theft - From Motor Vehicle - Petit</td>
<td>Brooke Tracy</td>
<td>09/20/2018</td>
<td>73 E Frambes Ave</td>
<td>40.004837</td>
<td>-83.00671</td>
</tr>
<tr>

<td>183016041-001</td>
<td>400 - Fraud</td>
<td>Xavier Casey</td>
<td>09/20/2018</td>
<td>1977 N 4th St</td>
<td>40.00384</td>
<td>-82.99849</td>
</tr>
<tr>

<td>180797975-001</td>
<td>201 - Theft of License Plate</td>
<td>AMANDA DAVEY</td>
<td>09/20/2018</td>
<td>414 W 7th</td>
<td>39.98955</td>
<td>-83.01686</td>
</tr>
<tr>

<td>180880603-001</td>
<td>110 - Felony Theft - Zone 4</td>
<td>Brian Buonocore</td>
<td>09/21/2018</td>
<td>1489 Grandview Ave</td>
<td>39.987755</td>
<td>-83.044556</td>
</tr>
<tr>

<td>180801269-001</td>
<td>254 - Assault</td>
<td>Kimberly Wooden</td>
<td>09/21/2018</td>
<td>Ifo 1446 N 5th St Apt A</td>
<td>Not found</td>
<td>Not found</td>
</tr>
<tr>

<td>180802653-001</td>
<td>551 - Criminal Damaging</td>
<td>Jason Kirkpatrick</td>
<td>09/22/2018</td>
<td>1353 N 4th St</td>
<td>39.990826</td>
<td>-82.99935</td>
</tr>
<tr>

<td>180804404-001</td>
<td>550 - Trespassing</td>
<td>No data provided</td>
<td>09/22/2018</td>
<td>1442 N 5th St Apt A</td>
<td>39.99285</td>
<td>-82.99798</td>
</tr>
<tr>

<td>180805416-001</td>
<td>712 - Disorderly Conduct</td>
<td>No data provided</td>
<td>09/22/2018</td>
<td>450 E Norwich Ave</td>
<td>40.006138</td>
<td>-82.99667</td>
</tr>
<tr>

<td>180805452-001</td>
<td>254 - Assault</td>
<td>Katarina Hodge</td>
<td>09/22/2018</td>
<td>1728 N High St</td>
<td>39.99774</td>
<td>-83.00759</td>
</tr>
<tr>

<td>180805585-001</td>
<td>550 - Trespassing</td>
<td>No data provided</td>
<td>09/23/2018</td>
<td>1770 N High St</td>
<td>39.998478</td>
<td>-83.00774</td>
</tr>
<tr>

<td>180805678-001</td>
<td>254 - Assault</td>
<td>Evan Bunis</td>
<td>09/23/2018</td>
<td>1100 N High St</td>
<td>39.984886</td>
<td>-83.00506</td>
</tr>
<tr>

<td>180805697-001</td>
<td>701 - Miscellaneous Offense</td>
<td>No data provided</td>
<td>09/23/2018</td>
<td>1770 N High St</td>
<td>39.998478</td>
<td>-83.00774</td>
</tr>
<tr>

<td>180806636-001</td>
<td>115 - Theft - Misdemeanor</td>
<td> [E] Floral Boutique</td>
<td>09/23/2018</td>
<td>215 King Ave</td>
<td>39.990364</td>
<td>-83.01214</td>
</tr>
<tr>

<td>180806875-001</td>
<td>200 - Motor Vehicle Theft</td>
<td>Connor Lucas</td>
<td>09/23/2018</td>
<td>1436 Meadow Rd</td>
<td>39.987778</td>
<td>-83.039024</td>
</tr>
<tr>

<td>180807009-001</td>
<td>200 - Motor Vehicle Theft</td>
<td>David Coulter</td>
<td>09/23/2018</td>
<td>338 E 18th Ave</td>
<td>40.002342</td>
<td>-82.99921</td>
</tr>


<tr>
</tbody></table>
<br><br>
<p>Which can then be transformed into a heatmap to analyze:</p>
 <br>
 <br>
<div id="mapid" class="centered-image"></div>
<br><br>
</div>

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.4/dist/leaflet.css"
integrity="sha512-puBpdR0798OZvTTbP4A8Ix/l+A4dHDD0DGqYW6RQ+9jxkRFclaxxQb/SJAWZfWAkuyeQUytO7+7N4QKrDh+drA=="
crossorigin=""/>
<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.3.4/dist/leaflet.js"
integrity="sha512-nMMmRyTVoLYqjP9hrbed9S+FzjZHW5gY1TWCHA5ckwXZBadntCNs8kEqAWdrb9O7rxbCaA4lKTIWjDXZxflOcA=="
crossorigin=""></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.heat/0.2.0/leaflet-heat.js"></script>
<style media="screen">
  #mapid { height: 500px;
    width:1000px;
   }
</style>
<script type="text/javascript">
  var mymap = L.map('mapid').setView([40.00233,-83.00 ], 13);
  L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoiZmx5c3VyZTE5OTciLCJhIjoiY2pta2xiMDRkMDIycTN1bnZiOGtuc3J1NCJ9.egiZOL0oX3eX4f-Atl9XWQ', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox.streets',
    accessToken: 'your.mapbox.access.token'
}).addTo(mymap);

var heat = L.heatLayer([
	[39.99746,	-83.00754, 0.2], // lat, lng, intensity
	[39.990437,	-83.01409, 0.5],
  [39.99746,	-83.00754],
  [39.990437,	-83.01409],
  [39.99104	, -83.003174],
  [40.004837	, -83.00671],
  [40.00384	, -82.99849],
  [39.98955	, -83.01686],
  [39.990826	, -82.99935],
  [39.99285	, -82.99798],
  [40.006138	, -82.99667],
  [39.99774	, -83.00759],
  [39.998478	, -83.00774],
  [39.984886	, -83.00506],
  [39.998478	, -83.00774],
  [39.990364	, -83.01214],
  [39.987778	, -83.039024],
  [40.002342	, -82.99921],
  [39.982735	, -82.998764]
], {radius: 50}).addTo(mymap);




</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Andrew Fleischer</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <%= yield %>

  </body>

</html>